import * as SpellIcons from '../assets/ui/loadout/charm';
import * as CONTENT from '../constants/content';

const charms = [
  {
    name: 'Wayward Compass',
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.waywardCompass,
  },
  {
    name: 'Gathering Swarm',
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.gatheringSwarm,
  },
  {
    name: 'Stalwart Shell',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.stalwartShell,
  },
  {
    name: 'Soul Catcher',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.soulCatcher,
  },
  {
    name: 'Shaman Stone',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.shamanStone,
  },
  {
    name: 'Soul Eater',
    cost: 4,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.soulEater,
  },
  {
    name: 'Dashmaster',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.dashmaster,
  },
  {
    name: 'Sprintmaster',
    cost: 1,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.sprintmaster,
  },
  {
    name: 'Grubsong',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.grubsong,
  },
  {
    name: `Grubberfly's Elegy`,
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.grubberflysElegy,
  },
  {
    name: 'Fragile Heart',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.fragileHeart,
  },
  {
    name: 'Unbreakable Heart',
    cost: 2,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.unbreakableHeart,
  },
  {
    name: 'Fragile Greed',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.fragileGreed,
  },
  {
    name: 'Unbreakable Greed',
    cost: 2,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.unbreakableGreed,
  },
  {
    name: 'Fragile Strength',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.fragileStrength,
  },
  {
    name: 'Unbreakable Strength',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.unbreakableStrength,
  },
  {
    name: 'Spell Twister',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.spellTwister,
  },
  {
    name: 'Steady Body',
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.steadyBody,
  },
  {
    name: 'Heavy Blow',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.heavyBlow,
  },
  {
    name: 'Quick Slash',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.quickSlash,
  },
  {
    name: 'Longnail',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.longNail,
  },
  {
    name: 'Mark of Pride',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.markOfPride,
  },
  {
    name: 'Fury of the Fallen',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.furyOfTheFallen,
  },
  {
    name: 'Thorns of Agony',
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.thornsOfAgony,
  },
  {
    name: 'Baldur Shell',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.baldurShell,
  },
  {
    name: 'Flukenest',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.flukenest,
  },
  {
    name: `Defender's Crest`,
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.defendersCrest,
  },
  {
    name: 'Glowing Womb',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.glowingWomb,
  },
  {
    name: 'Quick Focus',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.quickFocus,
  },
  {
    name: 'Deep Focus',
    cost: 4,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.deepFocus,
  },
  {
    name: 'Lifeblood Heart',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.lifebloodHeart,
  },
  {
    name: 'Lifeblood Core',
    cost: 3,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.lifebloodCore,
  },
  {
    name: `Joni's Blessing`,
    cost: 4,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.jonisBlessing,
  },
  {
    name: 'Hiveblood',
    cost: 4,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.hiveblood,
  },
  {
    name: 'Spore Shroom',
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.sporeShroom,
  },
  {
    name: 'Sharp Shadow',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.sharpShadow,
  },
  {
    name: 'Shape of Unn',
    cost: 2,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.shapeOfUnn,
  },
  {
    name: `Nailmaster's Glory`,
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.nailmastersGlory,
  },
  {
    name: 'Weaversong',
    cost: 2,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.weaversong,
  },
  {
    name: 'Dream Wielder',
    cost: 1,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.dreamWielder,
  },
  {
    name: 'Dreamshield',
    cost: 3,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.dreamshield,
  },
  {
    name: 'Carefree Melody',
    cost: 3,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.carefreeMelody,
  },
  {
    name: 'Grimmchild',
    cost: 2,
    origin: CONTENT.PACKS.THE_GRIMM_TROUPE,
    image: SpellIcons.grimmchild,
  },
  {
    name: 'Kingsoul',
    cost: 5,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.kingsoul,
  },
  {
    name: 'Void Heart',
    cost: 0,
    origin: CONTENT.PACKS.MAIN,
    image: SpellIcons.voidHeart,
  },
];

export default charms;
